name: smbcorr-docs
channels:
  - conda-forge
dependencies:
  - docutils
  - fontconfig
  - freetype
  - future
  - graphviz
  - lxml
  - markupsafe==2.0.1
  - matplotlib
  - numpy
  - numpydoc
  - pip
  - pyproj
  - python>=3.6
  - python-dateutil
  - scikit-learn
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - pip:
     - sphinx-argparse>=0.4
     - ..
